### ISSUE TITLE
Workspace configuration

### ISSUE THREAD

**Issue by jsantha** [memri/paint-game#1]
Take a look at the workspace I've initialized. Basic setup with TS, webpack dev server, eslint and CI pipeline.

- Do we need prettier? What is that for?

**Comment by Thesoreon** [comment]
Prettier is code formatter. We can provide a list of "rules" of how should be our code formatted (it can be integrated along with eslint), so we can ensure that whoever works on this repo will have correctly formatted code.  Also, it can save some time because you don't need to format code manually.

If we decide to use it, I'll do a PR with prettier implementation
